id: ACD3609C9
title: Prayer for the Long Life of Jamyang Khyentse Chökyi Lodrö
type: translation
pechas:
- IBF93AA88
- IFF9954BF
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:56:26.961750
  last_modified_at: 2023-01-04 11:56:26.961755
  collections:
  - Gatön Ngawang Lekpa Series
  - Works of Tibetan Masters
alignment_to_base:
  IBF93AA88/40E8: 84D4
  IFF9954BF/1AB4: 84D4
